// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeQOvaFBK9GCTPXy_bgoH9no2cB1vJfdg',
    appId: '1:386793433837:web:c4544dd3c1a2e909903ae4',
    messagingSenderId: '386793433837',
    projectId: 'responsible-student',
    authDomain: 'responsible-student.firebaseapp.com',
    storageBucket: 'responsible-student.appspot.com',
    measurementId: 'G-5PCQH7YPJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvBo2lrJljbokblhN1ohGpb_Z1VezmbhU',
    appId: '1:386793433837:android:67f37b31a15e76dd903ae4',
    messagingSenderId: '386793433837',
    projectId: 'responsible-student',
    storageBucket: 'responsible-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhkvDvPn8KMTV0H6BB_o7VLzQSX3eb_M',
    appId: '1:386793433837:ios:26369cfb50a20b7e903ae4',
    messagingSenderId: '386793433837',
    projectId: 'responsible-student',
    storageBucket: 'responsible-student.appspot.com',
    androidClientId:
        '386793433837-j11n6eggk0q2oidtbvnmdlgjdulttnv3.apps.googleusercontent.com',
    iosClientId:
        '386793433837-pbkv670tqdurfk7dkbh80kpctgbbjuhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsibleStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhkvDvPn8KMTV0H6BB_o7VLzQSX3eb_M',
    appId: '1:386793433837:ios:26369cfb50a20b7e903ae4',
    messagingSenderId: '386793433837',
    projectId: 'responsible-student',
    storageBucket: 'responsible-student.appspot.com',
    androidClientId:
        '386793433837-j11n6eggk0q2oidtbvnmdlgjdulttnv3.apps.googleusercontent.com',
    iosClientId:
        '386793433837-pbkv670tqdurfk7dkbh80kpctgbbjuhc.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsibleStudent',
  );
}
