name: Flutter

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.0"
          channel: "stable"

  build:
    runs-on: ${{ matrix.os }}
    needs: [setup]

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            flutter_path: /opt/hostedtoolcache/flutter
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v3
        with:
          path: ${{ matrix.flutter_path }}
          key: ${{ runner.os }}-flutter

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.3"
          channel: "stable"

      - name: Install dependencies
        working-directory: ./src/responsible_student
        run: flutter pub get

      # - name: Verify formatting
      #   working-directory: ./responsible_student
      #   run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: ./src/responsible_student
        run: flutter analyze --verbose

      # Enable when there are tests
      # - name: Run tests
      #   working-directory: ./responsible_student
      #   run: flutter test

      - name: Build app
        working-directory: ./src/responsible_student
        run: flutter build --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: src/responsible_student/build/app/outputs/flutter-apk/app.apk

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: nikonowiczp/Responsible-Student
          group: Testers
          token: ${{ secrets.APP_CENTER_TOKEN_ANDROID }}
          file: src/responsible_student/build/app/outputs/flutter-apk/app.apk
          buildNumber: ${{ github.run_number }}
          debug: true
